### ISSUE TITLE
Parse SAM template

### ISSUE THREAD

**Issue by elthrasher** [elthrasher/http-lambda-invoker#23]
Need to define some kind of API here. Ideally we support multiple functions by parsing the SAM template. This issue can be used to sketch ideas.

**Comment by S-Cardenas** [comment]
Things I think we need:

1. Ability to parse the SAM template and pick up functions attached to an API.
2. Ability to parse all layers and differentiate the ones which reference a local file from those that reference an AWS ARN. See the layers of `SampleFunction` below:
```
  SequelizeOrmLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sequelize-orm
      Description: Sequelize ORM for our node.js and our db
      ContentUri: ../layers/orm/
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "sample-function-${ApiStageParam}"
      CodeUri: ../lambdas/sample_function/
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 45
      MemorySize: 512
      Role: !GetAtt LambdaExecutionRole.Arn
      Layers:
        - arn:aws:lambda:us-east-1:1234567890:layer:imageMagickLayer:1
        - !Ref SequelizeOrmLayer
```
3. Pass in your local aws credentials from your machine. AWS SAM currently does this with the `--profile` flag on all commands. We should have something similar. Currently in the docker-compose template I am creating a volume from the `~/.aws` folder on machine and passing the credentials into the `docker-lambda` container through the AWS-SDK `SharedInFileCredentials`. I think it would be more beneficial to do it the AWS SAM way.

```
  graphqllambda:
    container_name: lambda
    image: lambci/lambda:nodejs12.x
    command: index.handler
    environment:
      API_STAGE: dev
    volumes:
      - ./lambdas/graph_ql:/var/task:ro,delegated
      - ./layers/cuidoc_orm/:/opt:ro,delegated
      - ~/.aws:/.aws
```

@elthrasher Let me know what you think

**Comment by elthrasher** [comment]
I haven't worked with lambda layers much. Are they not already supported by lambci? I assumed they would be.

What's the use case for real credentials?

I thought maybe I'd start with my example project and think about what it would look like using a sam template.
```yaml
version: '3.7'

services:
  api:
    container_name: api
    image: elthrasher/http-lambda-invoker
    environment:
      - LAMBDA_ENDPOINT=http://lambda:9001
      - PORT=8080
    ports:
      - '8080:8080'
    volumes:
      - ./template.yaml:/sam/template.yaml:ro,delegated
  lambda:
    container_name: lambda
    image: lambci/lambda:nodejs12.x
    command: app.MyFunctionName
    environment:
      - DOCKER_LAMBDA_STAY_OPEN=1
    volumes:
      - ./build:/var/task:ro,delegated
```

It could be as simple as that. It's probably still necessary for the lambda-invoker container to get an endpoint address for SAM, but now it'll route traffic to the correct function based on what's read in the template. Other things in the template, like runtime, timeouts, etc, would be ignored. I'm not trying to rewrite SAM here, just support a persistent version of it.

I noticed https://github.com/duartemendes/aws-sam-api-proxy just popped up. It's cool that other people are working on this problem. I'm going to stick with the docker-compose based approach because my use case will eventually be running new lambdas alongside legacy containers and I think this is the best way to do that.
